gems:
  - jekyll-mentions
  - jekyll-sitemap

footer-links:
  github: nicolasbock

pages_list:
  "Main": "/"
  "Spammpack": "/spammpack"
  "Spamm MiniApp": "/spamm-miniapp"
  "FreeON": "/freeon"
  "Data-Sets": "/data-sets"
  "Technical Reports": "/technical-reports"
  "FreeON Blog": "/blog"

url: http://www.freeon.org
baseurl: "/"
