gems:
  - jekyll-mentions

footer-links:
  github: nicolasbock

pages_list:
  "Main": "/"
  "Spammpack": "/spammpack"
  "Spamm MiniApp": "/spamm-miniapp"
  "FreeON": "/freeon"
  "Data-Sets": "/data-sets"

baseurl: "/"
